### ISSUE TITLE
[QUESTION] Should client_index.dart export models?

### ISSUE THREAD

**Issue by dJani97** [epam-cross-platform-lab/swagger-dart-code-generator#336]
### Please describe a problem.

I suppose the purpose of the `client_index.dart` file is that we'd only need to import this file when we want to use the generated code somewhere in our codebase.

This file only exports the generated ChopperService classes, for example mine looks simply like this:

    export 'openapi.swagger.dart' show Openapi;

But in other parts of my codebase I often find myself relying on the generated models too, having to import not only `client_index.dart`, but also the `.../swagger_generated_code/openapi.swagger.dart` file directly.

Is this bad practice?

### Describe the solution you'd like

For my use-case, the best solution would be to not only "`show`" the ChopperService itself, but also all the models related to it. 

So something like:

    export 'openapi.swagger.dart' show Openapi, ExampleDTO, AnotherExampleDTO, EtcDTO;

**Comment by Vovanella95** [comment]
Hi @dJani97  let me remember why we did this. I will answer you during the day

**Comment by Vovanella95** [comment]
Hi again @dJani97 

We decided to use `show` in `client_index.dart` because some swaggers can have same class names. In this case we will have compilation error. So, from my perspective `client_index.dart` is not needed, because it's useless when we have one swagger file and it's useless when we have many swaggers, because there is risk of same class names.

I will remove `client_index.dart` generation in future versions.

Any questions or proposals on this issue?

**Comment by dJani97** [comment]
Hey @Vovanella95, thank you for the detailed answer!

Removing it would clear up some confusion too, as there is not need to pick from two different import suggestions. It seems to be the better option for me.

Although if someone relied on this import so far, their code will break. So maybe wait till the next major release?

**Comment by Vovanella95** [comment]
Ok, fine, I will leave client_index for you. So can we close the issue @dJani97 ?

**Comment by dJani97** [comment]
I didn't use it, I'm just assuming that someone else might have. No other questions, thank you!

**Comment by Vovanella95** [comment]
@dJani97  closing the issue then :)
